'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ALPS() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ALPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ALPS10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ALPS10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ALPS2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ALPS2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ALPS3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ALPS3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ALPS4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ALPS4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ALPS5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ALPS5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ALPS6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ALPS6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ALPS7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ALPS7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ALPS8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ALPS8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ALPS9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ALPS9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DuckQuack() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DuckQuack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DuckQuack10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DuckQuack10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DuckQuack2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DuckQuack2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DuckQuack3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DuckQuack3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DuckQuack4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DuckQuack4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DuckQuack5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DuckQuack5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DuckQuack6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DuckQuack6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DuckQuack7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DuckQuack7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DuckQuack8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DuckQuack8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DuckQuack9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DuckQuack9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mechanical_Click() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mechanical_Click", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mechanical_Click10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mechanical_Click10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mechanical_Click2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mechanical_Click2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mechanical_Click3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mechanical_Click3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mechanical_Click4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mechanical_Click4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mechanical_Click5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mechanical_Click5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mechanical_Click6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mechanical_Click6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mechanical_Click7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mechanical_Click7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mechanical_Click8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mechanical_Click8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mechanical_Click9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mechanical_Click9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Membrane() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Membrane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Membrane10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Membrane10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Membrane2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Membrane2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Membrane3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Membrane3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Membrane4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Membrane4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Membrane5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Membrane5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Membrane6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Membrane6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Membrane7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Membrane7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Membrane8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Membrane8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Membrane9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Membrane9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlack() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlack10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlack10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlack2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlack2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlack3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlack3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlack4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlack4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlack5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlack5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlack6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlack6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlack7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlack7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlack8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlack8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlack9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlack9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlue() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlue10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlue10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlue2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlue2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlue3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlue3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlue4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlue4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlue5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlue5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlue6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlue6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlue7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlue7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlue8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlue8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBlue9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBlue9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBrown() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBrown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBrown10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBrown10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBrown2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBrown2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBrown3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBrown3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBrown4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBrown4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBrown5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBrown5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBrown6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBrown6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBrown7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBrown7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBrown8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBrown8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXBrown9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXBrown9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXRed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXRed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXRed10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXRed10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXRed2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXRed2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXRed3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXRed3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXRed4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXRed4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXRed5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXRed5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXRed6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXRed6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXRed7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXRed7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXRed8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXRed8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MXRed9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MXRed9", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
